subquery/network-clients

packages/network-clients/src/clients/queryClient.ts, packages/network-clients/src/config.ts, packages/network-clients/src/networkClient.ts, packages/network-clients/src/utils/network.ts, test/client.test.ts
https://onfinality.atlassian.net/browse/SQN-839
=> SQN-839: add max unstake amount  

package.json, packages/network-clients/package.json, packages/network-clients/src/clients/networkClient.ts, yarn.lock
Updating contract sdk version
Ticket # SQN-929
https://onfinality.atlassian.net/jira/software/projects/SQN/boards/14
=> update contract sdk

package.json, packages/network-query/queries/network/indexers.gql, test/networkClient.test.ts, test/queryClient.test.ts
Ticket # [SQN-991](https://onfinality.atlassian.net/browse/SQN-991)
- Enable flexibility of getIndexers query amount
- Simplify import path at test
- Remove repeat jest timeout setting & set timeout at jest command line
=> feat: imporve jest test & set timeout period at jest command line

.gitignore, package.json, packages/apollo-links/src/auth-http-link/authHttpLink.ts, packages/apollo-links/src/auth-link/authHelper.ts, packages/apollo-links/src/auth-link/authLink.ts, packages/apollo-links/src/index.ts, test/authLink.test.ts, yarn.lock
Add `authHttpLink` to simplify the way to use auth link in SDK
- Add `authHttpLink` which return authLink and httpLink together
=> Add: auth http link

packages/network-query/queries/network/statechannel.gql, packages/react-hooks/network.codegen.ts, test/queryClient.test.ts
add GetSteteChannels for graphql
=> add GetSteteChannels

.github/actions/create-prerelease/action.yml
=> fix yarn version cmd

packages/network-clients/src/clients/networkClient.ts, packages/network-clients/src/clients/queryClient.ts, test/networkClient.test.ts
- `getDelegating` amount with an address
=> feat:add getDelegating util & improvements

packages/network-query/queries/network/delegations.gql, test/queryClient.test.ts
add useFilteredDelegation query for Delegator Page Explorer
=> feat: add useFilteredDelegation query

.github/workflows/prerelease.yml, packages/network-query/README.md
When changes and build on react-query, react-hook should also build and release a new version
=> feat: update pipeline with react-hook

packages/network-clients/src/clients/networkClient.ts, packages/network-clients/src/models/indexer.ts
Cal commission rate and expose the sorted rate
=> feat: improve commissionRate cal

packages/network-query/queries/network/statechannel.gql
-  update stateChannelField on stateChannel Query
=> feat: update stateChannelField on stateChannel Query

packages/network-query/README.md, packages/network-query/queries/network/offers.gql
add GetOfferCount, remove hardcoded values
=> add GetOfferCount, remove hardcoded values

packages/network-clients/src/config.ts
Change the default RPC endpoint to moonbean
=> Update default rpc endpoint for testnet

packages/network-query/queries/network/staking.gql
Be able to pass in withdrawal status
=> update GetWithdrawls to be more generic

package.json, packages/network-clients/package.json, packages/network-clients/src/config.ts, test/networkClient.test.ts, yarn.lock
=> Update network name

package.json, packages/network-clients/package.json, yarn.lock
=> Upgrade contract sdk to latest version

packages/network-clients/.env, packages/network-clients/src/clients/networkClient.ts, packages/network-query/.env, packages/react-hooks/.env
Ticket [#SQN-1227](https://onfinality.atlassian.net/browse/SQN-1227)
- Update .env files codegen
- Update getDelegating function
=> Update getDelegating function

packages/network-query/queries/network/delegations.gql
add new query which can get delegation by indexer account
=> add new query for getdelegationbyindexer

packages/network-query/queries/network/delegations.gql
=> update query name

packages/apollo-links/src/auth-http-link/authHttpLink.ts, packages/apollo-links/src/auth-link/authLink.ts
- Fix the issue in authLink: get network chainId from auth url
=> Get networkChainId from authURl

packages/network-query/scripts/codegen.sh
=> solve entry issue

packages/network-query/queries/network/deployments.gql, packages/network-query/queries/network/indexers.gql
Need for handling pagination. Will add generic function in network clients later.
=> Add page info for score service

packages/network-query/queries/network/agreements.gql, test/queryClient.test.ts
Add a new network query GetProjectOngoingServiceAgreements to get ongoing service agreements with specific deploymentId
=> add GetProjectOngoingServiceAgreements query

packages/apollo-links/src/auth-link/authLink.ts, test/authLink.test.ts
- Fix error catch issue for authLink
=> Fix runtime error catch for authLink

README.md, package.json, packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json, yarn.lock
Release for @subql/apollo-links@0.4.0
* add changelogs
* add dependency for gh release script
* add developer guilds in README
=> [release] apollo links v0.4.0

packages/apollo-links/src/fallbackLink.ts
=> fix the apollo/client import to /core to avoid react dep

packages/apollo-links/src/authHttpLink.ts
=> Rename projectHttpLink to deploymentHttpLink

package.json, packages/network-clients/README.md, packages/network-clients/package.json, packages/network-clients/src/clients/networkClient.ts, packages/network-config/package.json, packages/network-config/src/config.ts, packages/network-query/package.json, packages/react-hooks/package.json, test/networkClient.test.ts, test/queryClient.test.ts, yarn.lock
New release PR for all the packages
- Upgrade contract SDK to latest version
- Bump release versions
=> [release] Upgrade contract SDK

.husky/pre-commit, .husky/pre-commit.sh, packages/apollo-links/src/agreementManager.ts, packages/apollo-links/src/auth-link/clusterAuthLink.ts, packages/apollo-links/src/authHttpLink.ts, packages/apollo-links/src/dynamicHttpLink.ts, packages/apollo-links/src/errorLink.ts, packages/apollo-links/src/fallbackLink.ts, packages/apollo-links/src/retryLink.ts, test/authLink.test.ts
=> Improve retries & logs

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json
=> [release] @subql/apollo-links v0.5.1

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json
=> [release] @subql/apollo-links 0.5.2

packages/network-clients/package.json, packages/network-config/package.json, packages/network-query/package.json, packages/react-hooks/package.json
=> chore: update

packages/network-clients/CHANGELOG.md, packages/network-config/CHANGELOG.md, packages/network-query/CHANGELOG.md, packages/react-hooks/CHANGELOG.md
=> [release] chore: change log

packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
=> [release] Chore/0.3.7

packages/network-clients/src/clients/networkClient.ts, packages/network-config/src/constants.ts, packages/network-query/network.codegen.ts, packages/network-query/queries/network/delegations.gql, packages/network-query/queries/network/deployments.gql, packages/network-query/queries/network/indexers.gql, packages/network-query/queries/network/statechannel.gql, packages/network-query/types.codegen.ts, test/authLink.test.ts, test/networkClient.test.ts
- remove metadata object from queries
=> update queries to remove metadata

packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
=> [release] chore/bump

.eslintrc, package.json, packages/apollo-links/src/agreementManager.ts, packages/apollo-links/src/auth-link/clusterAuthLink.ts, packages/apollo-links/src/authHttpLink.ts, packages/apollo-links/src/errorLink.ts, packages/apollo-links/src/query.ts, packages/apollo-links/src/types.ts, test/authLink.test.ts
- Update api call from auth service
- Clean auth link test
- Add test for `deployment auth link`
- Resolve https://github.com/subquery/subql/issues/1836
=> [WIP] - Update Apollo link with the changes from auth service

package.json, packages/network-clients/package.json, packages/network-config/package.json, yarn.lock
=> chore: bump contract sdk

packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json, yarn.lock
=> [release] bump 0.3.11

.yarn/versions/d0e9fc65.yml, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
=> [release] bump 0.3.13

packages/network-query/queries/leaderboard/topIndexer.gql, packages/network-query/queries/network/statechannel.gql
- Update top indexer query, https://github.com/subquery/network-explorer/pull/470/files
- Add query one stateChannel for fix [SQN-1540](https://onfinality.atlassian.net/browse/SQN-1540)
=> feat: update leaderboard and add one state channel

packages/network-query/queries/network/project.gql
Add `orderby` for `getProjects` query.
Relative this ticket  [SQN-1666](https://onfinality.atlassian.net/browse/SQN-1666)
=> feat: add orderby

packages/network-query/package.json, packages/react-hooks/package.json
=> chore: change version

packages/network-clients/src/clients/networkClient.ts, packages/network-clients/src/clients/queryClient.ts
=> chore: enhance type defination

packages/apollo-links/src/utils/orderManager.ts
- Support random start index for agreement and flex plan queries in Apollo Link
=> Support random start index

packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
=> [release] Bump 0.3.15

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json
=> [release] apollo-link 0.5.5

packages/network-query/queries/network/deployments.gql
- Add first and indexerId filter and orderby for `GetDeploymentIndexers`
=> feat: add filter on get deployment indexers

packages/apollo-links/src/core/clusterAuthLink.ts
=> fix auth token undefined

packages/apollo-links/package.json
=> [release] @subql/apollo-link@0.5.8

.github/workflows/prerelease.yml
=> fix: workflow

package.json, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-config/src/config.ts, yarn.lock
=> [release] @subql/network-clients@0.3.17

packages/network-query/queries/network/dashboard.gql
=> feat: add rewards by eras and indexerStakeSummaries Graphql query.

packages/network-query/network.codegen.ts, packages/network-query/queries/network/dashboard.gql, packages/network-query/queries/network/eraRewards.gql, packages/network-query/queries/network/indexerStake.gql, packages/network-query/types.codegen.ts, test/networkClient.test.ts, test/queryClient.test.ts
Queries for Dashboard and Indexer profile.
Includes test cases. Skip some cases that don't have data for test yet.
=> feat: query and test cases

packages/network-query/queries/network/eraRewards.gql, test/queryClient.test.ts
=> feat: get rewards query by indexer

packages/network-query/queries/network/eraRewards.gql
=> feat: era rewards

packages/apollo-links/CHANGELOG.md, packages/apollo-links/README.md, packages/apollo-links/package.json
=> [release] @subql/apollo-links@1.0.0

packages/network-query/queries/network/eraRewards.gql
- change era rewards filter condition.
=> feat: change era rewards filter condition

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json
=> [release] @subql/apollo-links@1.0.4

packages/apollo-links/src/core/clusterAuthLink.ts, packages/apollo-links/src/types.ts, test/authLink.test.ts
=> Update auth state for payg

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json
=> Bump `v1.0.6`

packages/network-query/queries/network/deployments.gql, packages/network-query/queries/network/eraStakes.gql, test/queryClient.test.ts
=> feat: era stake

packages/network-query/queries/network/dashboard.gql
=> fix: update dashboard

packages/network-query/queries/network/agreements.gql, packages/network-query/queries/network/plans.gql, packages/react-hooks/package.json
=> feat: add stable coin price token field

package.json, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json
=> [release] Bump network-clients@0.3.18, network-config@0.3.16

packages/apollo-links/README.md
- Update document for `Apollo links`
=> Update Auth Link Readme

packages/react-hooks/package.json, packages/react-hooks/src/useStableCoin.tsx, yarn.lock
- Transform all address to checksum address.
=> feat: use checksum address

packages/network-query/queries/network/airdrop.gql, packages/react-hooks/package.json
=> feat: change airdropuser

packages/apollo-links/src/core/clusterAuthLink.ts, packages/network-config/src/config.ts
=> fix missing indexer to context make score accurate

packages/apollo-links/README.md, packages/apollo-links/package.json
=> Release apollo link 231016

packages/apollo-links/src/authHttpLink.ts, packages/apollo-links/src/core/retryLink.ts
=> allow override maxRetries

packages/react-hooks/src/utils.ts
=> chore: reset type

packages/network-config/src/constants.ts
- Add a network config information.
=> feat: migrate network config information

packages/network-query/queries/network/project.gql
Add total reward for project.
- First change
- etc
=> feat: add total reward field

package.json, packages/network-clients/package.json, packages/network-clients/src/clients/contractClient.ts, packages/network-config/package.json, packages/network-config/src/config.ts, packages/network-config/src/constants.ts, packages/network-query/queries/network/agreements.gql, packages/network-query/queries/network/deployments.gql, packages/network-query/queries/network/offers.gql, packages/network-query/queries/network/plans.gql, packages/network-query/queries/network/project.gql, packages/react-hooks/package.json, test/queryClient.test.ts, yarn.lock
Reverts subquery/network-clients#213
=> Revert "Feat/sync with contract changes"

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
- Bump release version for new Testnet
=> Bump release version for testnet

packages/network-query/queries/network/offers.gql, packages/network-query/queries/network/project.gql
=> feat: offer counts & id

.yarn/versions/2be27383.yml, .yarn/versions/a537c6d1.yml, .yarn/versions/ac80254c.yml, .yarn/versions/bb8d2da0.yml, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
There have something version conflict, bump to new version to override.
=> [release] Bump: version 0.100.2

packages/react-hooks/network.codegen.ts
=> fix: use testnet

packages/apollo-links/README.md, packages/eth-provider/README.md, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-support/README.md, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
=> [release] @subql/apollo-links@1.2.3, @subql/eth-provider@0.1.0, @subql/network-support@0.1.0, @subql/react-hooks@0.3.17,@subql/network-clients@0.3.20

packages/eth-provider/CHANGELOG.md, packages/network-support/CHANGELOG.md
=> [release] @subql/network-support@0.1.0,@subql/eth-provider@0.1.0

packages/eth-provider/README.md
=> [release] @subql/eth-provider@0.1.0

packages/network-query/queries/network/statechannel.gql
=> feat: add state channels

packages/network-query/queries/network/statechannel.gql
=> feat: add state

packages/network-clients/CHANGELOG.md, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md
=> [Release] @subql/network-clients@0.111.0, @subql/react-hooks@0.111.0, @subql/netowrk-query@0.111.0

packages/network-clients/package.json, packages/react-hooks/CHANGELOG.md
=> [Release] clients & react-hooks 0.112.0

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json, yarn.lock
=> [Release] @subql/apollo-links@1.2.5

packages/network-clients/src/clients/contractClient.ts, packages/network-clients/src/clients/networkClient.ts, packages/network-clients/src/index.ts, packages/react-hooks/src/useStableCoin.tsx
- Change import to exact import.
- Remove re-export sdk from clients.
=> chore: change sdk

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json, packages/apollo-links/src/core/errorLink.ts, packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/orderManager.ts
=> feat: use both agreements flex plan

packages/network-query/queries/network/project.gql
- Add type filter on Projects.
=> feat: update graphql

packages/network-query/queries/network/agreements.gql, packages/network-query/queries/network/statechannel.gql
=> feat: add type on agreements & flex plan

packages/network-query/queries/network/project.gql
=> feat: agreements indexer

package.json, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-clients/src/clients/contractClient.ts, packages/network-clients/src/index.ts, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-config/src/constants.ts, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json, test/networkClient.test.ts, test/queryClient.test.ts, yarn.lock
=> [Release] migrate to base

packages/apollo-links/src/core/errorLink.ts, packages/apollo-links/src/core/responseLink.ts
=> Fix error handling and update score in response link

packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json
=> [Release] @subql/apollo-links@1.3.2

packages/network-config/src/constants.ts
=> update subql endpoint constants

packages/network-config/src/constants.ts, packages/network-query/queries/network/indexerAllocation.gql, packages/network-query/queries/network/indexerAllocationRewards.gql, packages/network-query/queries/network/project.gql
- Add booster/allocate/rewards query.
=> feat: Add booster/allocate/rewards query.

package.json, packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json, yarn.lock
=> bump: mainnet version

packages/eth-provider/CHANGELOG.md, packages/eth-provider/package.json
=> [Release] @subql/eth-provider@1.0.0

packages/network-clients/CHANGELOG.md, packages/network-clients/package.json, packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-config/src/constants.ts, packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
=> [Release] @subql/network-client@1.1.0, @subql/network-config@1.1.0, @subql/react-hooks@1.1.0, @subql/network-query@1.1.0

packages/network-config/CHANGELOG.md, packages/network-config/package.json, packages/network-config/src/config.ts, packages/network-config/src/constants.ts
=> [Release] @subql/network-config@1.1.1

packages/network-query/network.codegen.ts, packages/network-query/queries/network/indexerAllocation.gql, packages/network-query/queries/network/project.gql, packages/network-query/types.codegen.ts, packages/react-hooks/network.codegen.ts
=> fix: field name

packages/network-query/CHANGELOG.md, packages/network-query/package.json, packages/react-hooks/CHANGELOG.md, packages/react-hooks/package.json
=> [Release] @subql/network-query@1.1.1, @subql/react-hooks@1.1.1

packages/network-query/queries/network/dashboard.gql
=> feat: change dashboard total rewards

packages/network-query/queries/network/indexers.gql
=> feat: add indexer stake

packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/index.ts, packages/network-support/src/orderManager.ts, packages/network-support/test/fetch.test.ts, packages/network-support/tsconfig.json
=> implement a substitution for fetch

packages/network-query/queries/network/delegations.gql
=> feat: add indexer

.vscode/settings.json, packages/network-query/queries/network/delegations.gql
=> feat: add order

packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/utils/query.ts, packages/network-support/test/fetch.test.ts
=> add timeout to fetch

packages/network-clients/src/clients/networkClient.ts
=> feat: change commssion

packages/network-support/src/fetch.ts, packages/network-support/src/orderManager.ts, packages/network-support/src/types.ts
=> rpc fetch support fallback url

packages/network-clients/src/clients/networkClient.ts
=> feat: improve maxUnstakeAmount

packages/network-query/leaderboard.codegen.ts, packages/network-query/queries/network/deploymentBooster.gql, packages/network-query/types.codegen.ts
=> feat: booster query

packages/react-hooks/leaderboard.codegen.ts
=> fix: react-hooks

packages/network-clients/src/clients/networkClient.ts
=> fix: min stake

packages/network-query/queries/network/eraRewards.gql, packages/network-query/queries/network/eraStakes.gql
=> feat: update eraStake/eraRewards query.

packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/orderManager.ts, packages/network-support/src/scoreManager.ts, packages/network-support/src/utils/store.ts
=> orderManager return runner score

package.json, packages/network-clients/package.json, packages/network-clients/src/clients/networkClient.ts, packages/network-clients/src/utils/index.ts, packages/network-clients/src/utils/waitForSomething.ts, packages/network-config/package.json, packages/network-query/network.codegen.ts, packages/network-query/package.json, packages/network-query/queries/network/dashboard.gql, packages/network-query/queries/network/delegations.gql, packages/network-query/queries/network/delegatorApr.gql, packages/network-query/queries/network/eraRewards.gql, packages/network-query/queries/network/indexerApr.gql, packages/network-query/queries/network/indexerStake.gql, packages/network-query/queries/network/indexers.gql, packages/network-query/queries/network/staking.gql, packages/network-query/types.codegen.ts, packages/react-hooks/network.codegen.ts, packages/react-hooks/package.json, yarn.lock
=> feat: add apr relatives query

packages/network-query/network.codegen.ts, packages/network-query/queries/network/delegations.gql, packages/network-query/types.codegen.ts, packages/react-hooks/network.codegen.ts
- Add selfStake & totalStake to calculate capacity
=> feat: add stake for capacity

.eslintrc, packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json, packages/apollo-links/src/authHttpLink.ts, packages/apollo-links/src/core/clusterAuthLink.ts, packages/apollo-links/src/core/responseLink.ts, packages/eth-provider/src/provider.ts, packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/index.ts, packages/network-support/src/orderManager.ts, packages/network-support/src/scoreManager.ts, packages/network-support/src/stateManager.ts, packages/network-support/src/types.ts, packages/network-support/src/utils/hash.ts, packages/network-support/src/utils/query.ts, packages/network-support/src/utils/version.ts, yarn.lock
=> implement state manager

packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/orderManager.ts, packages/network-support/src/stateManager.ts
=> Fix-sync-state

packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/orderManager.ts, packages/network-support/src/stateManager.ts
=> fix fetch and invalidate state

packages/network-query/queries/network/delegations.gql
=> feat: add more filter

package.json, packages/apollo-links/CHANGELOG.md, packages/apollo-links/package.json, packages/eth-provider/CHANGELOG.md, packages/eth-provider/package.json, packages/eth-provider/src/provider.ts, packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/orderManager.ts, packages/network-support/src/utils/hash.ts, yarn.lock
=> fix crypto error on browser

package.json, packages/network-support/package.json, yarn.lock
=> fix network-support dependencies as a independent module

packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/utils/common.ts, packages/network-support/src/utils/index.ts
=> refactor: try error

packages/network-support/src/orderManager.ts
=> add ability to get state

packages/network-support/src/orderManager.ts, packages/network-support/src/scoreManager.ts, packages/network-support/src/utils/store.ts
1. reduce http2 weight. set 10 to 2;
2. add `X-SQ-No-Resp-Sig: true` header;
3. add manual weight;
4. change `selectedRunnersStore` to LRU for front-end;
=> feat: reduce http2 weight

packages/network-support/src/orderManager.ts, packages/network-support/src/scoreManager.ts, packages/network-support/src/utils/query.ts
=> improve http2 score logic

packages/network-support/src/fetch.ts, packages/network-support/src/orderManager.ts, packages/network-support/src/scoreManager.ts
1. add multiple weight;
2. deal `query overflow` error;
=> feat: add multiple weight

packages/network-support/src/orderManager.ts
=> fix: fix header sig

packages/network-support/src/utils/score.ts
add time cost as a factor in block weight.
=> feat: consider time cost for block weight

packages/network-support/src/stateManager.ts
add a time range barrier to multiple sync state
=> feat: mutex sync state

packages/network-support/src/fetch.ts
retry when `payg conflict` occurred.
=> fix: deal payg conflict

packages/network-support/src/fetch.ts
retreat to `payg conflict` sycn state.
=> fix: retreat to payg sign only

packages/network-support/src/fetch.ts
1. add some logs;
2. adjust fallback to try to fix NodePing error;
=> fix: try fix error

packages/network-support/package.json, packages/network-support/src/orderManager.ts, packages/network-support/src/scoreManager.ts, packages/network-support/src/types.ts
=> feat: add score detail

packages/network-support/src/fetch.ts
=> fix: workaround array body

packages/network-support/src/fetch.ts, packages/network-support/src/orderManager.ts
filter out indexers that can't handle batch rpc.
=> feat: filter batch rpc indexer

packages/network-support/src/scoreManager.ts
=> fix: revise

packages/network-support/src/fetch.ts
=> feat: add fatal error

packages/network-query/queries/network/dashboard.gql
=> feat: change delegator defination

packages/network-query/queries/network/dashboard.gql
=> chore: add start era filter

packages/network-query/network.codegen.ts, packages/network-query/queries/network/deploymentRewards.gql, packages/network-query/types.codegen.ts, packages/react-hooks/network.codegen.ts
=> feat: deployment era query

packages/network-clients/src/clients/networkClient.ts
=> feat: enhance ipfs

packages/network-support/CHANGELOG.md, packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/orderManager.ts
adapt Indexer new error structure.
=> feat: adapt error

packages/network-support/src/orderManager.ts, packages/network-support/src/scoreManager.ts, packages/network-support/src/utils/score.ts
=> feat: json log

packages/network-support/src/scoreManager.ts
=> fix: fix redis

packages/network-support/package.json
=> feat: add error log version

packages/network-support/src/scoreManager.ts, packages/network-support/src/utils/timeBarer.ts
* change notify content and format
* change time barrier ttl
=> feat: change notify format

packages/network-support/src/fetch.ts, packages/network-support/src/scoreManager.ts
refine 1011 error: no decrease score on `Invalid request` and `Method not found`
=> feat: detail 1011 error

packages/network-support/src/fetch.ts
no decrease score and retry on `graphql syntax error`
=> feat: bypass graphql syntax error

packages/network-support/src/scoreManager.ts
allow set manual score ratio for indexer-deployment
=> feat: allow set manual score ratio for indexer-deployment

packages/apollo-links/src/auth/authHelper.ts, packages/network-support/package.json, packages/network-support/src/fetch.ts, packages/network-support/src/orderManager.ts, packages/network-support/src/stateManager.ts, packages/network-support/src/types.ts, packages/network-support/src/utils/query.ts, packages/network-support/src/utils/store.ts
test and try improve agreement.
=> test and try improve agreement

packages/network-support/src/orderManager.ts
no cache order list when normally no order.
=> fix: normal no order

packages/network-query/queries/network/deployments.gql
add pagination for `GetDeploymentIndexersByIndexer`.
=> feat: add pagination

packages/react-hooks/package.json
=> chore: trigger

package.json, packages/react-hooks/package.json, packages/react-hooks/src/useStableCoin.tsx, yarn.lock
- Dynamic get price oracle address.
- 
=> feat: replace price oracle
