subquery/network-clients

- packages/network-clients/src/clients/queryClient.ts
- packages/network-query/queries/registry/totalLock.gql
- test/networkClient.test.ts
Expose `totalLock` eraAmount at network.
Ticket # [SQN-958](https://onfinality.atlassian.net/browse/SQN-958)
- `totalLock` record at network-subql 
- `totalLock` exposed at network-client sdk
> feat: add totalLock field

- package.json
- packages/network-clients/package.json
- packages/react-hooks/package.json
- test/authLink.test.ts
- yarn.lock
So now when network-queries version is updated, it will automatically set it in other packages.
> set network-query version to dev tag

- .github/workflows/prerelease.yml
- package.json
- packages/apollo-links/package.json
- packages/apollo-links/src/auth-link/authLink.ts
- yarn.lock
Set `graphql`  as peer dependency in `AuthLink` lib, it can resolve the issues for version conflicts on client side.
- Clean codes in authlink
- Set graphql as peer dependency
> Add `graphql` as peer dependency in auth link lib

- packages/apollo-links/package.json
- yarn.lock
Change `apollo-client` as peer dependency in `apollo-links`
> Update apollo-client as peer dependency

- packages/network-query/queries/network/agreements.gql
These additional queries are needed to filter service agreements when under consumer or indexer tab in explorer.
> add additional service agreement queries

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
Change the order of publish client and query SDK, as the client sdk dependent on query sdk, need to publish query sdk first before publish client sdk
> Change the order of publish package

- package.json
- packages/apollo-links/package.json
- packages/network-clients/package.json
- packages/network-clients/src/clients/contractClient.ts
- packages/network-query/package.json
- packages/network-query/queries/network/staking.gql
- packages/react-hooks/package.json
- yarn.lock
- Upgrade contract SDK which include the fix for unbonding 
- Add new method for networkClient: `canStartNewUnbonding` to check whether an account can start new unbonding, the app can use this method to check the availability before trigger the `unstake` or `undelegate` transaction @CaiYiLiang 
>  Update contract sdk

- packages/apollo-links/src/authHttpLink.ts
- test/authLink.test.ts
Split `authHttpLink()` into `dictHttpLink` & `projectHttpLink`
for the reason
* make it clear in which scenario which one should be used
* both of them only make sense when use with an auth service, but not the case when passing pk directly. 
* for pk case, we can use a different entry method
- First change
- etc
> separate the link create function for dict & project

- packages/network-config/src/constants.ts
- packages/network-query/queries/network/indexers.gql
- packages/network-query/types.codegen.ts
- test/networkClient.test.ts
- Add filter for `GetIndexers`.
- Change `avoidOptionals` to false on some cases, that will generated some type like `type p = { xxx?: string }` rather than `type p = { xxx: string }`. So when clients use `filter` on some query would not be fill all the fields of `filter` 
- Reset network subql endpoint of testnet, that will fix `unstake` problem and something relative `getIndex` function.
> feat: add filter for get indexers and reset testnet config

- packages/apollo-links/CHANGELOG.md
- packages/apollo-links/package.json
> [release] chore: bp 0.5.3

- packages/network-clients/src/clients/networkClient.ts
- packages/network-clients/src/clients/queryClient.ts
- `GraphqlQueryClient` can accept the second arg that type could be `ApolloClient` or `ApolloClientOptions`.
- `NetworkClient` add a public method for set `_gqlClient`. 
Ticket # [SQN-1671](https://onfinality.atlassian.net/browse/SQN-1671)
> feat: support custom apollo clients

- packages/apollo-links/src/core/clusterAuthLink.ts
- packages/apollo-links/src/utils/orderManager.ts
- Fix consuming cached token
- Set fixed 2 available agreement for polkadot dictionary (From Kepler), sending 20 queries request. Here are the test logs
```
request new token for indexer 0xa8ddFCf5b5aC088d4d9DaA76fE8b743351578399
request new token for indexer 0xa8ddFCf5b5aC088d4d9DaA76fE8b743351578399 success
use url: https://subquery-indexer.liveraven.net/query/QmZGAZQ7e1oZgfuK4V29Fa5gveYK3G2zEwvUzTZKNvSBsm
request new token for indexer 0xf6A7FddeB551b8a8C5cc57D9c0Ebc14ce34ce401
request new token for indexer 0xf6A7FddeB551b8a8C5cc57D9c0Ebc14ce34ce401 success
use url: http://66.206.2.162/query/QmZGAZQ7e1oZgfuK4V29Fa5gveYK3G2zEwvUzTZKNvSBsm
use url: https://subquery-indexer.liveraven.net/query/QmZGAZQ7e1oZgfuK4V29Fa5gveYK3G2zEwvUzTZKNvSBsm
use url: …
```
> fix: consuming cached token

- packages/network-clients/src/utils/index.ts
- packages/react-hooks/src/renderAsync.ts
- packages/react-hooks/src/utils.ts
> feat: add calc progress number

- __mocks__/axios.ts
- package.json
- packages/apollo-links/src/auth/authHelper.ts
- packages/apollo-links/src/core/authLink.ts
- packages/apollo-links/src/core/fallbackLink.ts
- packages/apollo-links/src/core/responseLink.ts
- packages/apollo-links/src/utils/logger.ts
- packages/apollo-links/src/utils/orderManager.ts
- test/authLink.test.ts
- yarn.lock
- Use `https://api.subquery.network/sq/subquery/kepler-testnet` for fallback test url, also can set by `process.env.FALLBACK_URL`.
- Use `000000000000000000000000000000000000000000000000000000000000000f` for default SK.
- Remove `tokenToStateChannel`, it never used. [more information](https://github.com/subquery/network-clients/pull/148/commits/810b473bc85c21ebd325cbc2eb84cea04c1c26a5#diff-857502561e224f5cfa55c3516689ce69c9fd7150c1cba0a1f9442c595c99a288L42)
- Add `token` param for `AuthLink`, for reuse an exist token(in this PR for test `authHelper isTokenExpired` and relatives logic).
- Use `signMessage` for sign message in `requestAuthToken` and make a test case for it.
[SQN-1758](https://onfinality.atlassian.net/browse/SQN-1758) …
> fix: test case

- packages/apollo-links/src/core/clusterAuthLink.ts
- packages/apollo-links/src/utils/query.ts
- test/authLink.test.ts
- test/queryClient.test.ts
- handle no orders in `clusterAuthLink`
- Add a test case for query without available agreements
> Fix query without available orders

- packages/apollo-links/CHANGELOG.md
- packages/apollo-links/package.json
- packages/apollo-links/src/core/responseLink.ts
- test/authLink.test.ts
- yarn.lock
- Support new communication protocol.
> [release] @subql/apollo-links@1.1.0 

- packages/apollo-links/CHANGELOG.md
- packages/apollo-links/package.json
- packages/apollo-links/src/authHttpLink.ts
- packages/apollo-links/src/core/errorLink.ts
- packages/apollo-links/src/core/orderManager.ts
- packages/apollo-links/src/core/responseLink.ts
- packages/network-query/network.codegen.ts
- packages/network-query/types.codegen.ts
- test/authLink.test.ts
- test/networkClient.test.ts
- test/queryClient.test.ts
- Always request `state`. Whatever have GraphqlError or not.
- Expose `useFallbackImmediateAfterGraphqlError`, if it is true, will use fallback re-request this query.
- Adjust Graphql error reducing score from 10 to 100, network error reducing score from 50 to 20.
- Expect `remote` send to `/channel/state`.
Ticket # ([SQN-1986](https://onfinality.atlassian.net/browse/SQN-1986))
> feat: re-request when face a graphql error

- .github/workflows/prerelease.yml
- .yarn/versions/2be27383.yml
- packages/apollo-links/package.json
- packages/network-clients/package.json
- packages/network-config/package.json
- packages/network-query/package.json
- packages/react-hooks/package.json
> fix prerelease: set fetch-depth as 0

- .yarnrc.yml
- package.json
- packages/network-clients/CHANGELOG.md
- packages/network-clients/package.json
- packages/network-config/CHANGELOG.md
- packages/network-config/package.json
- packages/network-config/src/config.ts
- packages/network-config/src/constants.ts
- packages/network-query/leaderboard.codegen.ts
- packages/network-query/types.codegen.ts
- packages/react-hooks/CHANGELOG.md
- packages/react-hooks/leaderboard.codegen.ts
- packages/react-hooks/package.json
- packages/react-hooks/src/utils.ts
- yarn.lock
> [Release] @subql/network-client@0.111.0, @subql/network-config@0.111.0, @subql/react-hooks@0.111.0

- package.json
- packages/apollo-links/CHANGELOG.md
- packages/apollo-links/package.json
- packages/apollo-links/src/core/clusterAuthLink.ts
- packages/apollo-links/src/core/responseLink.ts
- packages/network-support/package.json
- yarn.lock
- apollo-client 3.7.0 doesn't handle the abort error, upgrade to 3.8.8.
- Fix an unexpected behavior when indexer not enough score to re-try.
> [Release] @subql/apollo-links@1.2.4

- packages/network-clients/src/clients/networkClient.ts
- test/networkClient.test.ts
Add new function `getIndexerMetadata` in client SDK, this function is helpful in some service projects to get the indexerMetadata only and ignore the other request in `getIndexer` function.
> Add fun to `getIndexerMetadata` only

- packages/network-support/src/fetch.ts
- packages/network-support/src/orderManager.ts
- packages/network-support/test/fetch.test.ts
> improve logging

- packages/apollo-links/CHANGELOG.md
- packages/apollo-links/package.json
- packages/eth-provider/CHANGELOG.md
- packages/eth-provider/package.json
- packages/network-support/CHANGELOG.md
- packages/network-support/package.json
> [release] @subql/network-support@1.2.4 @subql/apollo-lnks@1.4.2 @subql/eth-provider@1.1.1

- packages/network-support/src/utils/store.ts
- Support clean localStorage when got storage excess error
> Support clean localStorage when got excess error

- packages/network-support/src/fetch.ts
- packages/network-support/src/orderManager.ts
- packages/network-support/src/scoreManager.ts
- packages/network-support/src/types.ts
- packages/network-support/src/utils/store.ts
> feat: ratelimit score weight
